### ISSUE TITLE
CPU name an speed

### ISSUE THREAD

**Issue by jarno83** [TheNikiz/android_kernel_samsung_hawaii#1]
Hi, in Settings -> About phone at cpu it shows 0. Should it be CPU name? At pda net it shows - Broadcom BCM21663.

No-frills CPU Control - shows that default min and max speeds are 999mhz and governor is performance. Works great at min 312 and max 999 and gov. interactive.

Thanks,
Great Work :) :+1:

**Comment by TheNikiz** [comment]
@jarno83 That is because /proc/cpuinfo shows the name of first core as 0, for some reason. I can't work on this phone right now, because I hard-bricked it by fooling around with the bootloader.. (I thought it would boot the backup instead if something went wrong, but nope..)

**Comment by jarno83** [comment]
Ok, thanks.
